#!/usr/bin/env bash
#afplay /System/Library/Sounds/Purr.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Basso.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Blow.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Bottle.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Frog.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Funk.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Glass.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Hero.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Morse.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Ping.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Pop.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Purr.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Sosumi.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Submarine.aiff >/dev/null 2>&1 &
#afplay /System/Library/Sounds/Tink.aiff >/dev/null 2>&1 &
